user                   = "shd@cloud-temple.lan"
password               = "Pfe@2022B1"
vsphere_server         = "vc-vstack-019-test.virtualstack.tn"
name_rp                =  "RP1"
name_dc                = "DC-DTX1"
name_vsphere_datastore = "ds001-test-svc1-stor3-dtx1"
name_vsphere_network   = "CTT-Stage2022"
